In [4]:
using LinearAlgebra

In [2]:
function resolve_diagonal(A, b)
    x = b\A
    return x
end

resolve_diagonal (generic function with 1 method)

In [121]:
function resolve_triangular_superior(A, b)
    n = length(b)
    x = zeros(n)
    for i = n:-1:1
        x[i] = b[i]
        for j = i+1:n
            x[i] = x[i] - (A[i,j]*x[j])
        end
        x[i] = x[i]/A[i, i]
    end
    return x
end

resolve_triangular_superior (generic function with 1 method)

In [126]:
function resolve_triangular_inferior(A, b)
    n = length(b)
    x = zeros(n)
    for i = 1:n
        x[i] = b[i]
        for j = 1:(i - 1)
            x[i] = x[i] - (A[i,j]*x[j])
        end
        x[i] = x[i]/A[i, i]
    end
    return x
end

resolve_triangular_inferior (generic function with 1 method)

In [94]:
A = Matrix{Float64}(I,5,5)
size(A)
A
A[1,2] = 5
A

5×5 Matrix{Float64}:
 1.0  5.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [99]:
function decomposicao_LU(A)
    # Pega o número de linhas de A
    n, = size(A)
    # Gera a matriz que será L 
    L = Matrix{Float64}(I,n,n)
    # Fazemos uma cópia de A. Será nossa matriz triangular superior
    U = copy(A)
    # Constante que multiplica as linhas
    v = 0
    for i = 1:(n-1)
        pivo = U[i,i]
        # Para cada linha abaixo da linha do pivo, realizamos o escalonamento
        for j = (i+1):n 
            # Constante que multiplicará toda uma linha
            v = U[j,i]/pivo
            # Multiplica todos elementos da linha correspondente para balancear o sistema
            for k = 1:n  
                U[j,k] = U[j,k] - U[i,k]*v
            end
            # Zeramos os elementos manualmente devido ao erro de precisão da máquina
            U[j,i] = 0 
            # Gera a matriz triangular inferior elemento por elemento
            L[j,i] = v
        end
    end
    return L,U
end         

decomposicao_LU (generic function with 1 method)

In [101]:
A =37*randn(5,5)
L,U = decomposicao_LU(A)
L*U ≈ A 
#U

true

In [92]:
A[3,2]

15.883089742125456

In [112]:
decomposicao_LU(A)

([1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0], [3.0 2.0 4.0; 0.0 0.33333333333333337 0.6666666666666667; 0.0 0.0 -8.0])

In [83]:
B = zeros(5,5)
n, = size(B)
n

5

In [130]:
function inversa_LU(A)
    L, U = decomposicao_LU(A)
    n, = size(A)
    y = zeros(n, n)
    A_inv = zeros(n, n)
    ident = zeros(n, n)
    for i = 1:n
        ident[i,i] = 1
    end
    for i = 1:n
        y[:,i] = resolve_triangular_inferior(L, ident[:,i])
        A_inv[:, i] = resolve_triangular_superior(U, y[:, i])
    end
    return A_inv
end
                

inversa_LU (generic function with 1 method)

In [114]:
L, U = decomposicao_LU(A)

([1.0 0.0 0.0; 0.3333333333333333 1.0 0.0; 1.3333333333333333 1.0000000000000002 1.0], [3.0 2.0 4.0; 0.0 0.33333333333333337 0.6666666666666667; 0.0 5.551115123125783e-17 -8.0])

In [123]:
n, = size(U)
b = ones(n)
x = resolve_triangular_superior(U, b)
U*x

3-element Vector{Float64}:
 1.0
 0.9999999999999999
 1.0000000000000002

In [127]:
n, = size(L)
b = ones(n)
x = resolve_triangular_inferior(L, b)
L*x

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [131]:
inversa_LU(A)

3×3 Matrix{Float64}:
  1.0    -2.0     0.0
 -1.25    2.75    0.25
  0.125   0.125  -0.125