# Nome: Matheus da Silva Oliveira
# DRE: 118178020

## 1

Será usada a [biblioteca Test](https://docs.julialang.org/en/v1/stdlib/Test/) para facilitar nos units tests.

In [117]:
using LinearAlgebra
using Test

### RESOLVE_DIAGONAL

Como sabemos, quando a matriz $A$ é diagonal, o sistema $Ax=b$ é determinado, pois todos os $x_i$ são determinados por apenas uma divisão, desde que a diagonal de $A$ seja não nula. Caso fosse, deveriámos olhar para o vetor $b$, mas não precisamos nos preocupar com este caso agora. Sendo assim, determinamos todos os elementos do vetor $x$ através da fórmula
$$
x_i = \frac{b_i}{a_{ii}}
$$

In [118]:
"""
    resolve_diagonal(A,b)
    
Retorna a matriz coluna x que é o resultado do sistema linear diagonal Ax=b.
A é uma matriz nxn e b nx1.
"""
function resolve_diagonal(A, b)
    # Computa n, que será o número de linhas da matriz x
    n = length(b)
    x = zeros(n)
    # Computa o vetor x
    for i=1:n
        x[i] = b[i] / A[i,i]
    end
    return x
end

resolve_diagonal

#### Testes

As matrizes para os testes são geradas randomicamente. A matriz identidade $I$ concedida pela biblioteca *LinearAlgebra* foi usada para gerar as matrizes diagonais.

In [119]:
# n é o número de linhas e colunas da matriz A_i e o número de linhas da matriz b_i
n = 5
A1 = randn()*Matrix{Float64}(I,n,n)
b1 = randn(n)

n = 6
A2 = randn()*Matrix{Float64}(I,n,n)
b2 = randn(n)

n = 2
A3 = randn()*Matrix{Float64}(I,n,n)
b3 = randn(n)

2-element Vector{Float64}:
 0.144008336256361
 0.007322648979642422

In [120]:
x1 = resolve_diagonal(A1,b1)
@test A1*x1 ≈ b1 

Test Passed

In [121]:
x2 = resolve_diagonal(A2,b2)
@test A2*x2 ≈ b2 

Test Passed

In [122]:
x3 = resolve_diagonal(A3,b3)
@test A3*x3 ≈ b3 

Test Passed

### RESOLVE_TRIANGULAR_SUPERIOR

Como visto nos vídeos do Abel, a fórmula para cada $x_i$ é dado por 
$$
x_i = \frac{b_i-\sum_{j=i+1}^{n} a_{ij}x_j}{a_{ii}}
$$
onde $a_{ij}$ são os elementos da matriz $A$.

In [123]:
"""
    resolve_triangular_superior(A,b)
    
Retorna a matriz coluna x que é o resultado do sistema linear Ax=b, onde
A é uma matriz nxn triangular superior e b possui tamanho nx1.
"""
function resolve_triangular_superior(A, b)
    # Computa n, que será o número de linhas da matriz x
    n = length(b)
    x = zeros(n)
    #= Para cada linha i de A e b, começando na última linha e terminando na primeira,
    computamos cada variável nas colunas por substituição direta=# 
    for i = n:-1:1
        # x_i = b_i no começo de cada iteração
        x[i] = b[i]
        for j = i+1:n
            # Subtraímos de b_i o somatório da fórmula
            x[i] = x[i] - (A[i,j]*x[j])
        end
        # Dividimos por a_ii 
        x[i] = x[i]/A[i,i]
    end
     # Retorna a matriz coluna resultado
    return x
end

resolve_triangular_superior

#### Testes

Como o $det(A) \neq 0$, sendo A uma matriz triangular superior ou inferior, então o sistema é determinado, visto que o determinante de uma matriz triangular superior ou inferior é o produto de sua diagonal principal. Sendo assim, utilizamos a função [UpperTriangular](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.UpperTriangular) para gerar as matrizes $A_i$. 

In [124]:
n = 5
A1 = randn(n,n)
A1 = UpperTriangular(A1)
b1 = randn(n)

n = 6
A2 = randn(n,n)
A2 = UpperTriangular(A2)
b2 = randn(n)

n = 2
A3 = randn(n,n)
A3 = UpperTriangular(A3)
b3 = randn(n)

2-element Vector{Float64}:
  2.0390187289197312
 -1.9433461548910869

In [125]:
x1 = resolve_triangular_superior(A1,b1)
@test A1*x1 ≈ b1 

Test Passed

In [126]:
x2 = resolve_triangular_superior(A2,b2)
@test A2*x2 ≈ b2 

Test Passed

In [127]:
x3 = resolve_triangular_superior(A3,b3)
@test A3*x3 ≈ b3 

Test Passed

### RESOLVE_TRIANGULAR_INFERIOR

Como visto nos vídeos do Abel, a fórmula para cada $x_i$ é dado por 
$$
x_i = \frac{b_i-\sum_{j=1}^{i-1} a_{ij}x_j}{a_{ii}}
$$

In [128]:
"""
    resolve_triangular_inferior(A,b)
    
Retorna a matriz coluna x que é o resultado do sistema linear Ax=b, onde
A é uma matriz nxn triangular inferior e b possui tamanho nx1.
"""
function resolve_triangular_inferior(A, b)
    # Computa n, que será o número de linhas da matriz x
    n = length(b)
    x = zeros(n)
    #= Para cada linha i de A e b, começando na primeira linha e terminando na última,
    computamos cada variável nas colunas por substituição direta=# 
    for i = 1:n
        # x_i = b_i no começo de cada iteração
        x[i] = b[i]
        for j = 1:(i - 1)
            # Subtraímos de b_i o somatório da fórmula
            x[i] = x[i] - (A[i,j]*x[j])
        end
        # Dividimos por a_ii 
        x[i] = x[i]/A[i,i]
    end
    # Retorna a matriz coluna resultado
    return x
end

resolve_triangular_inferior

#### Testes

O resultado visto na parte da matriz triangular superior pode ser utilizado aqui para geração dos testes. Dessa forma, seguimos o mesmo algoritmo, mas agora utilizamos a função [LowerTriangular](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.LowerTriangular) para gerar matrizes triangulares inferiores.

In [129]:
n = 5
A1 = randn(n,n)
A1 = LowerTriangular(A1)
b1 = randn(n)

n = 6
A2 = randn(n,n)
A2 = LowerTriangular(A2)
b2 = randn(n)

n = 2
A3 = randn(n,n)
A3 = LowerTriangular(A3)
b3 = randn(n)

2-element Vector{Float64}:
 -0.9704986210770746
 -0.005849452139337621

In [130]:
x1 = resolve_triangular_inferior(A1,b1)
@test A1*x1 ≈ b1 

Test Passed

In [131]:
x2 = resolve_triangular_inferior(A2,b2)
@test A2*x2 ≈ b2 

Test Passed

In [132]:
x3 = resolve_triangular_inferior(A3,b3)
@test A3*x3 ≈ b3 

Test Passed

### DECOMPOSICAO_LU

In [133]:
"""
    decomposicao_LU(A)
    
Retorna as matrizes L,U nxn que correspondem a igualdade L*U = A.
A é uma matriz nxn.
"""
function decomposicao_LU(A)
    # Pega o número de linhas de A
    n, = size(A)
    # Gera a matriz que será L 
    L = Matrix{Float64}(I,n,n)
    # Fazemos uma cópia de A para não alterar a entrada. Essa matriz será nossa matriz triangular superior.
    U = copy(A)
    # Inicializamos a constante que multiplica as linhas
    v = 0
    # A variável i representa a linha do pivo atual
    for i = 1:(n-1)
        pivo = U[i,i]
        # Para cada linha abaixo da linha do pivo, realizamos o escalonamento
        for j = (i+1):n 
            # Constante que multiplicará toda uma linha
            v = U[j,i]/pivo
            # Multiplica todos elementos da linha correspondente para balancear o sistema
            for k = 1:n  
                U[j,k] = U[j,k] - U[i,k]*v
            end
            # Zeramos os elementos manualmente devido ao erro de precisão da máquina
            U[j,i] = 0 
            # Gera a matriz triangular inferior elemento por elemento
            L[j,i] = v
        end
    end
    # Retorna a tupla (L,U)
    return L,U
end         

decomposicao_LU

#### Testes

In [134]:
A1 = [3.0 2.0 4.0; 
    1.0 1.0 2.0; 
    4.0 3.0 -2.0]

A2 = [1.0 2.0 3.0; 
    4.0 -2.0 6.0; 
    1.0 4.0 5.0]

A3 = [8.0 -4.0 -2.0; 
    -4.0 10.0 -2.0; 
    -2.0 -2.0 10.0]

3×3 Matrix{Float64}:
  8.0  -4.0  -2.0
 -4.0  10.0  -2.0
 -2.0  -2.0  10.0

In [135]:
L,U = decomposicao_LU(A1)
@test L*U ≈ A1

Test Passed

In [136]:
L,U = decomposicao_LU(A2)
@test L*U ≈ A2

Test Passed

In [137]:
L,U = decomposicao_LU(A3)
@test L*U ≈ A3

Test Passed

### INVERSA

Para encontrar a matriz inversa, é preciso resolver o sistema $AA^{-1} = I$, onde $A^{-1}$ será determinado. Contudo, podemos pensar em resolver os sistemas $AA^{-1}_j = I_j$ onde $A^{-1}_j$ e $I_j$ correspondem as colunas $j$ da inversa de $A$ e da matriz identidade. Fazendo isso, podemos determinar completamente $A^{-1}$.

In [138]:
"""
   inversa(A)
    
Retorna a inversa A^-1 da matriz A
A é uma matriz nxn.
"""
function inversa(A)
    # Calcula o tamanho da inversa
    n, = size(A)
    # Inicializa A^-1
    A_inv = zeros(n, n)
    # Gera a matriz identidade 
    Ident = Matrix{Float64}(I,n,n)
    # Computa A*A^(-1)_j = I_j para cada coluna j 
    L,U = decomposicao_LU(A)
    for j=1:n
         Y = resolve_triangular_inferior(L,Ident[:,j])
         A_inv[:,j] = resolve_triangular_superior(U,Y)
    end
    # Retorna a inversa
    return A_inv
end      

inversa

#### Testes

Para gerar os testes, precisamos que cada matriz $A$ gerada possua $det(A) \neq 0$, pois matrizes não invertíveis possuem determinante igual a 0. Com isso, o algoritmo computa uma matriz A aleatoriamente. Se $det(A) = 0$, calculamos uma nova matriz A.

In [139]:
n = 5
A = randn(n,n)
while(det(A) == 0)
    A = randn(n,n)
end
A_inv = inversa(A)
Ident = Matrix{Float64}(I,n,n)
# Testa se A*A^-1 ≈ I
@test A*A_inv ≈ Ident

Test Passed

In [140]:
n = 10
A = randn(n,n)
while(det(A) == 0)
    A = randn(n,n)
end
A_inv = inversa(A)
Ident = Matrix{Float64}(I,n,n)
# Testa se A*A^-1 ≈ I
@test A*A_inv ≈ Ident

Test Passed

In [141]:
n = 27
A = randn(n,n)
while(det(A) == 0)
    A = randn(n,n)
end
A_inv = inversa(A)
Ident = Matrix{Float64}(I,n,n)
# Testa se A*A^-1 ≈ I
@test A*A_inv ≈ Ident

Test Passed

#### Complexidade

Primeiro, ocorre a decomposição LU que possui complexidade $O(n^3)$. Para cada coluna $A^{-1}_j$ e $I_j$, chamamos as funções *resolve_triangular_superior* e *resolve_triangular_inferior*, então temos $n$ operações. Ambas as funções anteriores possuem complexidade $O(n^2)$, então temos uma complexidade $O(n^3)$ juntando com as $n$ operações para cada coluna. Somando as duas ordem, podemos dizer que a função inversa implementada possui complexidade $O(n^3)$.

*Refs.:*
- https://www.youtube.com/watch?v=5RWstMXFohQ
- https://en.wikipedia.org/wiki/Invertible_matrix

## 3

In [142]:
function discretiza(n)
    A = zeros(n,n)
    A[:,1] .= 25
    A[1,:] .= 20 
    A[:,n] .= 20 
    A[n,:] .= 30
    for i=1:(n-1)
        for j=1:(n-1)
            
        end
    end
end

discretiza (generic function with 1 method)

In [143]:
function discretiza(n)
    A = zeros(n)
    b = zeros(n)
    for i=1:n^2
        A[i,i] = 1
        if i <= n 
            b[i] += 20/4
        end
        if (i-1)%n == 0
            b[i] += 25/4
        end
        if i%n == 0
            b[i] += 20/4
        end
        if i >= n*(n-1) + 1
            b[i] += 30/4
        end
    end
end

discretiza (generic function with 1 method)

In [144]:
n = 7
 A = zeros(n,n)
A[:,1] .= 25
A[1,:] .= 20 
A[:,n] .= 20 
A[n,:] .= 30
A

7×7 Matrix{Float64}:
 20.0  20.0  20.0  20.0  20.0  20.0  20.0
 25.0   0.0   0.0   0.0   0.0   0.0  20.0
 25.0   0.0   0.0   0.0   0.0   0.0  20.0
 25.0   0.0   0.0   0.0   0.0   0.0  20.0
 25.0   0.0   0.0   0.0   0.0   0.0  20.0
 25.0   0.0   0.0   0.0   0.0   0.0  20.0
 30.0  30.0  30.0  30.0  30.0  30.0  30.0

## 4

A função *resolve* soluciona o sistema $Ax=b$ através de decomposição LU, onde A é uma matriz $nxn$. Isso pode ser feito através dos passos
\begin{align*}
Ax&=b\\
LUx&=b\\
LY&=b &\text{onde } Y &= Ux\\
UX &= Y
\end{align*}
Dessa forma $X$ é o vetor coluna que procuramos.

In [145]:
"""
    resolve(A,b)
    
Retorna a matriz coluna x que é o resultado do sistema linear Ax=b, onde
A é uma matriz nxn e b possui tamanho nx1.
"""
function resolve(A,b)
    L,U = decomposicao_LU(A)
    Y = resolve_triangular_inferior(L,b)
    return resolve_triangular_superior(U,Y)
end

resolve

#### Testes

In [146]:
n = 4
A1 = randn(n,n)
b1 = A1 * ones(n)

n = 5
A2 = randn(n,n)
b2 = A2 * ones(n)

n = 10
A3 = randn(n,n)
b3 = A3 * ones(n)

10-element Vector{Float64}:
  0.13600075434621756
 -0.45711743444600383
 -2.077268838972131
 -1.8478305518091456
 -5.257967869423813
 -1.5378472800837228
  0.8220992803581075
  2.2073007960538162
  3.0574206155202983
 -4.325981879825736

In [147]:
x1 = resolve(A1,b1)
@test A1*x1 ≈ b1

Test Passed

In [148]:
x2 = resolve(A2,b2)
@test A2*x2 ≈ b2

Test Passed

In [149]:
x3 = resolve(A3,b3)
@test A3*x3 ≈ b3

Test Passed

Para montar o sistema, podemos pensar que todos os canos conservam o volume de água que passa por eles, em outras palavras, todo volume de água que entra em um cano deve sair dele. Com isso em mente, podemos determinar o sistema
\begin{align*}
 x_1-2000-5000 &= 0 & \text{A} \\ 
x_2-1500-2000 &= 0 & \text{B}\\
x_3-8000-1000 &= 0 & \text{C}\\
-x_2-x_4+x_6 &= 0 & \text{F}\\
-x_5+x_7-3000 &= 0 & \text{G}\\
-x_6-x_7+x_8-500&= 0 & \text{H}\\
-x_1+x_4-30000 &= 0 & \text{D}\\
-x_3+x_5-3000 &= 0 & \text{E}\\
\end{align*}
Colocando todas as constantes do lado direito das equações e montando o sistema $Ax=c$, chegamos ao resultado

In [150]:
A = [
    1 0 0 0 0 0 0 0;
    0 1 0 0 0 0 0 0;
    0 0 1 0 0 0 0 0;
    0 -1 0 -1 0 1 0 0;
    0 0 0 0 -1 0 1 0;
    0 0 0 0 0 -1 -1 1;
    -1 0 0 1 0 0 0 0;
    0 0 -1 0 1 0 0 0;
   ]

c = [
    2000+5000;
    1500+2000;
    8000+1000;
    0;
    3000;
    500; 
    30000;
    3000;  
]

resolve(A,c)

8-element Vector{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

Agora o sistema com a variável $x_9$ será
\begin{align*}
 x_1-2000-5000 &= 0 & \text{A} \\ 
x_2-1500-2000 &= 0 & \text{B}\\
x_3-8000-1000 &= 0 & \text{C}\\
-x_2-x_4+x_6 &= 0 & \text{F}\\
-x_5+x_7-3000 &= 0 & \text{G}\\
-x_6-x_7+x_8-500&= 0 & \text{H}\\
-x_1+x_4-30000 -x_9 &= 0 & \text{D}\\
-x_3+x_5-3000+x_9 &= 0 & \text{E}\\
\end{align*}
Com isso adicionamos a coluna abaixo a matriz $A$ e resolvemos o sistema novamente.

In [151]:
A1 = hcat(A,[0; 0; 0; 0; 0; 0; -1; 1])
resolve(A1,c)

8-element Vector{Float64}:
  7000.0
  3500.0
  9000.0
 37000.0
 12000.0
 40500.0
 15000.0
 56000.0

Como estamos tratando apenas matrizes $A_{nxn}$, o resultado não é modificado, visto que a última coluna não é considerada pois $A1$ possui tamanho $8x9$.